version: '3.8'
services:
  catalog_deployer:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - ROOT_DIR=/storage
    volumes:
      - ./tests/test_dir:/storage


volumes:
  storage:
